devices([
  "iPhone 16 Pro Max",
  "iPhone Air",
  "iPad Pro 13-inch (M4)"
])

languages([
  "en-US",
  "pt-BR"
])

workspace("./ios/weathersuncreenapp.xcworkspace")
scheme("WeatherSunscreenAppScreenshots")
output_directory("./fastlane/screenshots/ios")
clear_previous_screenshots(true)
stop_after_first_error(true)
number_of_retries(1)
