devices([
  "iPhone 16 Pro Max",
  "iPhone 16",
  "iPad Pro (12.9-inch) (6th generation)"
])

languages([
  "en-US",
  "pt-BR"
])

scheme("WeatherSunscreenAppScreenshots")
output_directory("./fastlane/screenshots/ios")
resolution("all")
clear_previous_screenshots(true)
stop_after_first_error(true)
number_of_retries(1)
test_without_building(true)
